//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/ServicioWCF")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUsuarioWCF.IUsuarioServiceWCF")]
    public interface IUsuarioServiceWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServiceWCF/ObtenerUsuarios", ReplyAction="http://tempuri.org/IUsuarioServiceWCF/ObtenerUsuariosResponse")]
        DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario[] ObtenerUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServiceWCF/ObtenerUsuarios", ReplyAction="http://tempuri.org/IUsuarioServiceWCF/ObtenerUsuariosResponse")]
        System.Threading.Tasks.Task<DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario[]> ObtenerUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServiceWCF/ObtenerUsuarioPorId", ReplyAction="http://tempuri.org/IUsuarioServiceWCF/ObtenerUsuarioPorIdResponse")]
        DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario ObtenerUsuarioPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServiceWCF/ObtenerUsuarioPorId", ReplyAction="http://tempuri.org/IUsuarioServiceWCF/ObtenerUsuarioPorIdResponse")]
        System.Threading.Tasks.Task<DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario> ObtenerUsuarioPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServiceWCF/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarioServiceWCF/CrearUsuarioResponse")]
        bool CrearUsuario(DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServiceWCF/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarioServiceWCF/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<bool> CrearUsuarioAsync(DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServiceWCF/ActualizarUsuario", ReplyAction="http://tempuri.org/IUsuarioServiceWCF/ActualizarUsuarioResponse")]
        bool ActualizarUsuario(DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServiceWCF/ActualizarUsuario", ReplyAction="http://tempuri.org/IUsuarioServiceWCF/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServiceWCF/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarioServiceWCF/EliminarUsuarioResponse")]
        bool EliminarUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServiceWCF/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarioServiceWCF/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServiceWCF/GrabarLog", ReplyAction="http://tempuri.org/IUsuarioServiceWCF/GrabarLogResponse")]
        bool GrabarLog(string evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServiceWCF/GrabarLog", ReplyAction="http://tempuri.org/IUsuarioServiceWCF/GrabarLogResponse")]
        System.Threading.Tasks.Task<bool> GrabarLogAsync(string evento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceWCFChannel : DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.IUsuarioServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceWCFClient : System.ServiceModel.ClientBase<DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.IUsuarioServiceWCF>, DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.IUsuarioServiceWCF {
        
        public UsuarioServiceWCFClient() {
        }
        
        public UsuarioServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario[] ObtenerUsuarios() {
            return base.Channel.ObtenerUsuarios();
        }
        
        public System.Threading.Tasks.Task<DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario[]> ObtenerUsuariosAsync() {
            return base.Channel.ObtenerUsuariosAsync();
        }
        
        public DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario ObtenerUsuarioPorId(int id) {
            return base.Channel.ObtenerUsuarioPorId(id);
        }
        
        public System.Threading.Tasks.Task<DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario> ObtenerUsuarioPorIdAsync(int id) {
            return base.Channel.ObtenerUsuarioPorIdAsync(id);
        }
        
        public bool CrearUsuario(DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario usuario) {
            return base.Channel.CrearUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> CrearUsuarioAsync(DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario usuario) {
            return base.Channel.CrearUsuarioAsync(usuario);
        }
        
        public bool ActualizarUsuario(DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario usuario) {
            return base.Channel.ActualizarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(DigitalBank.PresentacionCliente.ServiceReferenceUsuarioWCF.Usuario usuario) {
            return base.Channel.ActualizarUsuarioAsync(usuario);
        }
        
        public bool EliminarUsuario(int id) {
            return base.Channel.EliminarUsuario(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int id) {
            return base.Channel.EliminarUsuarioAsync(id);
        }
        
        public bool GrabarLog(string evento) {
            return base.Channel.GrabarLog(evento);
        }
        
        public System.Threading.Tasks.Task<bool> GrabarLogAsync(string evento) {
            return base.Channel.GrabarLogAsync(evento);
        }
    }
}
